### ISSUE TITLE
[Bug]: HttpError: Not Found - https://docs.github.com/rest/repos/contents#create-or-update-file-contents

### ISSUE THREAD

**Issue by williamium3000** [Enveloppe/obsidian-enveloppe#371]
### Issue validation

- [x] I checked the issue to prevent duplicate
- [x] I checked my configurations files and the documentation

### Plugin version

1.0.0

### Describe the bug

This is the test md file in obsidian:
```
---
date: "{{date}}"
tags:
  - tag1
  - tag2
title: "{{title}}"
slug: "{{time}}"
share: true
canonicalURL: 
keywords: 
description: 
series: series1
lastmod: 
lang: en
cover.image: 
author: william
dir: content/post
---
this is a hello world page
```

I have set up all the github related configurations and test connection works fine.

But I encounter the following error:
```
HttpError: Not Found - https://docs.github.com/rest/repos/contents#create-or-update-file-contents
```

And the file is not uploaded to my GitHub either.
My GitHub is publically available. 
https://github.com/williamium3000/myblog

### Minimal Reproducible Example

```markdown
---
date: "{{date}}"
tags:
  - tag1
  - tag2
title: "{{title}}"
slug: "{{time}}"
share: true
canonicalURL: 
keywords: 
description: 
series: series1
lastmod: 
lang: en
cover.image: 
author: william
dir: content/post
---
this is a hello world page
```

### Configuration

```JSON
{
  "github": {
    "branch": "main",
    "automaticallyMergePR": true,
    "dryRun": {
      "enable": false,
      "folderName": "github-publisher"
    },
    "tokenPath": "%configDir%/plugins/%pluginID%/env",
    "api": {
      "tiersForApi": "Github Free/Pro/Team (default)",
      "hostname": ""
    },
    "workflow": {
      "commitMessage": "[PUBLISHER] Merge",
      "name": ""
    },
    "verifiedRepo": true
  },
  "upload": {
    "behavior": "yaml",
    "defaultName": "content/post",
    "rootFolder": "content",
    "yamlFolderKey": "dir",
    "frontmatterTitle": {
      "enable": false,
      "key": "title"
    },
    "replaceTitle": [],
    "replacePath": [],
    "autoclean": {
      "enable": false,
      "excluded": []
    },
    "folderNote": {
      "enable": false,
      "rename": "index.md",
      "addTitle": {
        "enable": false,
        "key": "title"
      }
    },
    "metadataExtractorPath": ""
  },
  "conversion": {
    "hardbreak": true,
    "dataview": true,
    "censorText": [
      {
        "entry": "/\\]\\(([^)\\.]+)\\.md/",
        "replace": "]({{< relref \"$1.md\" >}}",
        "flags": "",
        "after": true,
        "inCodeBlocks": false
      },
      {
        "entry": "/cover\\.image/",
        "replace": "cover:\\n    image",
        "flags": "",
        "after": false
      },
      {
        "entry": "/\\]\\(([^/\\)]+?)\\.(png|jpg|jpeg|webp|gif)/",
        "replace": "](/images/$1.$2",
        "flags": "",
        "after": true
      },
      {
        "entry": "/\\!\\[\\[([^/\\]]+?)\\.(png|jpg|jpeg|webp|gif)\\|(\\d+)(x(\\d+))?\\]\\]/",
        "replace": "{{< figure src=\"/images/$1.$2\"  width=\"$3\" height=\"$5\">}}",
        "flags": "",
        "after": false
      },
      {
        "entry": "/\\!\\[\\[([^/\\]]+?)\\.(png|jpg|jpeg|webp|gif)\\|([^\\|]*?)(\\|(\\d+)(x(\\d+))?)?\\]\\]/",
        "replace": "{{< figure src=\"/images/$1.$2\" caption=\"$3\" width=\"$5\" height=\"$7\">}}",
        "flags": "",
        "after": false
      }
    ],
    "tags": {
      "inline": true,
      "exclude": [],
      "fields": []
    },
    "links": {
      "internal": false,
      "unshared": false,
      "wiki": true,
      "slugify": "lower"
    }
  },
  "embed": {
    "attachments": true,
    "overrideAttachments": [],
    "keySendFile": [],
    "notes": false,
    "folder": "static/images",
    "convertEmbedToLinks": "keep",
    "charConvert": "->",
    "forcePushAttachments": [],
    "useObsidianFolder": false
  },
  "plugin": {
    "shareKey": "share",
    "excludedFolder": [],
    "copyLink": {
      "enable": false,
      "links": "",
      "removePart": [],
      "transform": {
        "toUri": true,
        "slugify": "lower",
        "applyRegex": []
      }
    },
    "setFrontmatterKey": "Set"
  },
  "tabsId": "github-configuration"
}
```

### Relevant log output

```bash session
HttpError: Not Found - https://docs.github.com/rest/repos/contents#create-or-update-file-contents
```

### Obsidian information

```bash session
SYSTEM INFO:
	Obsidian version: v1.7.7
	Installer version: v1.7.7
	Operating system: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000 24.1.0
	Login status: logged in
	Language: en
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 19
	Plugins enabled: 19
		1: Excalidraw v2.6.8
		2: Dataview v0.5.67
		3: Advanced Tables v0.22.1
		4: Templater v2.9.1
		5: Iconize v2.14.6
		6: Outliner v4.8.1
		7: Omnisearch v1.25.1
		8: Linter v1.27.1
		9: Importer v1.6.13
		10: Text Generator v0.7.43
		11: Pandoc Plugin v0.4.1
		12: Copilot v2.7.7
		13: Paste URL into selection v1.7.0
		14: ZotLit v1.1.9
		15: Image Toolkit v1.4.2
		16: Copy document as HTML v0.8.1
		17: Image auto upload v4.1.0
		18: Enveloppe v7.4.0
		19: Image Inserter v0.7.0

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by Mara-Li** [comment]
What did you set in the configuration for the repository?

**Comment by williamium3000** [comment]
I did not set any configuration for the github repo. It's a public repo.
Here is the URL for the repo https://github.com/williamium3000/myblog

**Comment by Mara-Li** [comment]
Bruh.
Not the first time this happend. Github api is not reliable.
Will check that when I have the time

**Comment by Mara-Li** [comment]
By any chance, did you have protected the main branch ?
At wish step the error appear ?
I noticed that reproducing this kind of bug is difficult, so, if possible, I need your entire log.

**Comment by williamium3000** [comment]
I don't think it's protected
![Image](https://github.com/user-attachments/assets/1d9a911c-56ea-4ce8-b0c9-66d2c1c59908)

How can I provide you with the entire log?

It happens after I use the cmd+p and then Enveloppe: upload single current active note. Then it reports the error.
![Image](https://github.com/user-attachments/assets/ba5e641f-c8c9-4661-a833-05b66dabb8cf)

Despite it says success after the error. I check my github and the note is not uploaded.

**Comment by Mara-Li** [comment]
Strange.
Normally, there should be a "normal" 404 error (as the file not exist) but the file should be created.
I forked and used your settings, and I don't have any error. I even recreated a default token and didn't have any problem.

Can you please open the log console (CTRL+Maj+I) and copy paste everything?
Which command did you use?

**Comment by Mara-Li** [comment]
For branch protection: ![Image](https://github.com/user-attachments/assets/55b16830-eac4-4970-b851-a805e5c6c5cb)

**Comment by williamium3000** [comment]
Yeah it's not protected.
![Image](https://github.com/user-attachments/assets/bcc163de-3f02-4e90-aa77-7b28dc05dc49)

**Comment by williamium3000** [comment]
> Strange. Normally, there should be a "normal" 404 error (as the file not exist) but the file should be created. I forked and used your settings, and I don't have any error. I even recreated a default token and didn't have any problem.
> 
> Can you please open the log console (CTRL+Maj+I) and copy paste everything? Which command did you use?

If it works on the forked repo, maybe there is some error with mu configuration?

**Comment by williamium3000** [comment]
logs from the log console.
```
pulls:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
plugin:obsidian-mkdocs-publisher:183 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'join')
    at eval (plugin:obsidian-mkdocs-publisher:183:40710)
    at e.addTextArea (app.js:1:1402645)
    at EnveloppeSettingsTab.renderEmbedConfiguration (plugin:obsidian-mkdocs-publisher:183:40616)
    at EnveloppeSettingsTab.renderSettingsPage (plugin:obsidian-mkdocs-publisher:183:18420)
    at async HTMLDivElement.eval (plugin:obsidian-mkdocs-publisher:183:17842)
refs:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
plugin:obsidian-mkdocs-publisher:202 2024-12-15 14:23:33.467	INFO		Enveloppe	Branch already exists (notes-12-15-2024 on williamium3000/myblog - Using it.
content%2Fpost%2Fhello.md:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
content%2Fpost%2Fhello.md:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
plugin:obsidian-mkdocs-publisher:202 2024-12-15 14:23:33.801	FATAL		Enveloppe	
 HttpError  Not Found - https://docs.github.com/rest/repos/contents#create-or-update-file-contents, HttpError, 404, [object Object], [object Object]
error stack:
  • 	
	
  • 	
	
  • 	
	
  • 	
	
  • 	
	
  • 	
	
pulls:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
plugin:obsidian-mkdocs-publisher:183 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'join')
    at eval (plugin:obsidian-mkdocs-publisher:183:40710)
    at e.addTextArea (app.js:1:1402645)
    at EnveloppeSettingsTab.renderEmbedConfiguration (plugin:obsidian-mkdocs-publisher:183:40616)
    at EnveloppeSettingsTab.renderSettingsPage (plugin:obsidian-mkdocs-publisher:183:18420)
    at async HTMLDivElement.eval (plugin:obsidian-mkdocs-publisher:183:17842)
refs:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
plugin:obsidian-mkdocs-publisher:202 2024-12-17 11:28:17.749	INFO		Enveloppe	Branch already exists (notes-12-15-2024 on williamium3000/myblog - Using it.
content%2Fpost%2Fhello.md:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
content%2Fpost%2Fhello.md:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
plugin:obsidian-mkdocs-publisher:202 2024-12-17 11:28:18.255	FATAL		Enveloppe	
 HttpError  Not Found - https://docs.github.com/rest/repos/contents#create-or-update-file-contents, HttpError, 404, [object Object], [object Object]
error stack:
  • 	
	
  • 	
	
  • 	
	
  • 	
	
  • 	
	
  • 	
	
pulls:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
refs:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
plugin:obsidian-mkdocs-publisher:202 2024-12-17 11:28:28.949	INFO		Enveloppe	Branch already exists (notes-12-15-2024 on williamium3000/myblog - Using it.
content%2Fpost%2Fhello.md:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
content%2Fpost%2Fhello.md:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
plugin:obsidian-mkdocs-publisher:202 2024-12-17 11:28:29.140	FATAL		Enveloppe	
 HttpError  Not Found - https://docs.github.com/rest/repos/contents#create-or-update-file-contents, HttpError, 404, [object Object], [object Object]
error stack:
  • 	
	
  • 	
	
  • 	
	
  • 	
	
  • 	
	
  • 	
	
pulls:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
refs:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
plugin:obsidian-mkdocs-publisher:202 2024-12-17 11:28:39.344	INFO		Enveloppe	Branch already exists (notes-12-15-2024 on williamium3000/myblog - Using it.
content%2Fpost%2Fhello.md:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
content%2Fpost%2Fhello.md:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
plugin:obsidian-mkdocs-publisher:202 2024-12-17 11:28:39.551	FATAL		Enveloppe	
 HttpError  Not Found - https://docs.github.com/rest/repos/contents#create-or-update-file-contents, HttpError, 404, [object Object], [object Object]
error stack:
  • 	
	
  • 	
	
  • 	
	
  • 	
	
  • 	
	
  • 	
	
pulls:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
refs:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
plugin:obsidian-mkdocs-publisher:202 2024-12-17 11:28:55.095	INFO		Enveloppe	Branch already exists (notes-12-15-2024 on williamium3000/myblog - Using it.
content%2Fpost%2Fhello.md:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
content%2Fpost%2Fhello.md:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
plugin:obsidian-mkdocs-publisher:202 2024-12-17 11:28:55.391	FATAL		Enveloppe	
 HttpError  Not Found - https://docs.github.com/rest/repos/contents#create-or-update-file-contents, HttpError, 404, [object Object], [object Object]
error stack:
  • 	
	
  • 	
	
  • 	
	
  • 	
	
  • 	
	
  • 	
	
pulls:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
plugin:obsidian-mkdocs-publisher:22 
        
        
       POST https://api.github.com/repos/williamium3000/myblog/git/refs 404 (Not Found)
fetchWrapper @ plugin:obsidian-mkdocs-publisher:22
request2 @ plugin:obsidian-mkdocs-publisher:22
eval @ plugin:obsidian-mkdocs-publisher:22
Promise.then
register @ plugin:obsidian-mkdocs-publisher:22
Object.assign.endpoint @ plugin:obsidian-mkdocs-publisher:22
newBranchOnRepo @ plugin:obsidian-mkdocs-publisher:42
await in newBranchOnRepo
newBranch @ plugin:obsidian-mkdocs-publisher:42
shareOneNote @ plugin:obsidian-mkdocs-publisher:27
await in shareOneNote
checkCallback @ plugin:obsidian-mkdocs-publisher:27
ZU @ app.js:1
t.onChooseItem @ app.js:1
t.onChooseSuggestion @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
(anonymous) @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
plugin:obsidian-mkdocs-publisher:202 2024-12-17 22:52:15.915	INFO		Enveloppe	Branch already exists (notes-12-15-2024 on williamium3000/myblog - Using it.
plugin:obsidian-mkdocs-publisher:22 
        
        
       GET https://api.github.com/repos/williamium3000/myblog/contents/content%2Fpost%2Fhello.md?ref=notes-12-15-2024 404 (Not Found)
fetchWrapper @ plugin:obsidian-mkdocs-publisher:22
request2 @ plugin:obsidian-mkdocs-publisher:22
eval @ plugin:obsidian-mkdocs-publisher:22
Promise.then
register @ plugin:obsidian-mkdocs-publisher:22
Object.assign.endpoint @ plugin:obsidian-mkdocs-publisher:22
upload @ plugin:obsidian-mkdocs-publisher:42
uploadText @ plugin:obsidian-mkdocs-publisher:42
uploadOnMultipleRepo @ plugin:obsidian-mkdocs-publisher:42
await in uploadOnMultipleRepo
publish @ plugin:obsidian-mkdocs-publisher:42
await in publish
shareOneNote @ plugin:obsidian-mkdocs-publisher:27
await in shareOneNote
checkCallback @ plugin:obsidian-mkdocs-publisher:27
ZU @ app.js:1
t.onChooseItem @ app.js:1
t.onChooseSuggestion @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
(anonymous) @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
plugin:obsidian-mkdocs-publisher:22 
        
        
       PUT https://api.github.com/repos/williamium3000/myblog/contents/content%2Fpost%2Fhello.md 404 (Not Found)
fetchWrapper @ plugin:obsidian-mkdocs-publisher:22
request2 @ plugin:obsidian-mkdocs-publisher:22
eval @ plugin:obsidian-mkdocs-publisher:22
Promise.then
register @ plugin:obsidian-mkdocs-publisher:22
Object.assign.endpoint @ plugin:obsidian-mkdocs-publisher:22
upload @ plugin:obsidian-mkdocs-publisher:42
await in upload
uploadText @ plugin:obsidian-mkdocs-publisher:42
uploadOnMultipleRepo @ plugin:obsidian-mkdocs-publisher:42
await in uploadOnMultipleRepo
publish @ plugin:obsidian-mkdocs-publisher:42
await in publish
shareOneNote @ plugin:obsidian-mkdocs-publisher:27
await in shareOneNote
checkCallback @ plugin:obsidian-mkdocs-publisher:27
ZU @ app.js:1
t.onChooseItem @ app.js:1
t.onChooseSuggestion @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
(anonymous) @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
plugin:obsidian-mkdocs-publisher:202 2024-12-17 22:52:16.567	FATAL		Enveloppe	
 HttpError  Not Found - https://docs.github.com/rest/repos/contents#create-or-update-file-contents, HttpError, 404, [object Object], [object Object]
error stack:
  • 	
	
  • 	
	
  • 	
	
  • 	
	
  • 	
	
  • 	
	
plugin:obsidian-mkdocs-publisher:22 
        
        
       POST https://api.github.com/repos/williamium3000/myblog/pulls 404 (Not Found)
```

**Comment by williamium3000** [comment]
any clues?

**Comment by Mara-Li** [comment]
Sorry, but I have a life…

**Comment by Mara-Li** [comment]
Can  i get the path of the hello testing file?
I put it in content/post/hello.md without noticing error.
It is possible to get the error stack that are hiden in your message?

**Comment by williamium3000** [comment]
It seems like for some reason, despite I can curl https://api.github.com/repos/williamium3000/myblog/git/refs in the terminal, 404 is reported in the obsidian.
![Image](https://github.com/user-attachments/assets/9872cc3d-d10e-4d02-a218-c29dc8114cd2)

**Comment by williamium3000** [comment]
I created a new obsidian repo and it still won't work.

**Comment by williamium3000** [comment]
I have also tried different tokens and tokens that has been tested (can used to upload images to imagebed in github). Still not working. I have also tried turning off my firewall. Still the same.

**Comment by williamium3000** [comment]
I try using different laptops. Still.
Regarding the token, I have set all the permissions.
![Image](https://github.com/user-attachments/assets/7401bd0c-dab6-4a66-8195-2721887d3a44)

**Comment by Mara-Li** [comment]
I really don't know, and why the fucking error doesn't give me the stack T-T.

**Comment by williamium3000** [comment]
yeah. no problem. I can add you to my repo. It's new repo, so nothing to lose.

**Comment by williamium3000** [comment]
I have added you to my repo

**Comment by Mara-Li** [comment]
wil check it when I have the time. So sorry to don't found the error and provide a quick solution :(

**Comment by williamium3000** [comment]
It's ok. No worries!

**Comment by Mara-Li** [comment]
The fact I'm able to make a proper PR on your repository but not you make this bug more and more cursed.
The only thing I want to check is the network tabs, while testing to send only one file.

Maybe github Rest API is somehow block on your side?

**Comment by williamium3000** [comment]
It really weird as I can curl rest API in my terminal, but not my obsidian. I notice that, but turning off my firewall does not help. DO you have any suggestions on how to check whether github Rest API is somehow block on my side?

**Comment by williamium3000** [comment]
I am in a hotel outside and was able to get it to work now.  https://github.com/williamium3000/myblog/blob/main/test.md

But why the hell my home network is not working?

**Comment by Mara-Li** [comment]
I think something block github on your network ?
Do you have a proxy in your home configuration?

Or we can start to pray the omnimessiah…

**Comment by williamium3000** [comment]
I don't think I have any proxy. 
If I can "curl -i https://api.github.com/repos/williamium3000/myblog/git/refs", what else would be the problem?

**Comment by felixzrte** [comment]
getting this same bug.

**Comment by Mara-Li** [comment]
Could you please open the dev console (CTRL + MAJ + I) and go into the "network tab" and try to use the plugin?
I would check the log to understand why some people have theses errors.

**Comment by amatya-aditya** [comment]
I'm getting this error too.

**Comment by Mara-Li** [comment]
I don't think it's the same cause and problem than William. Could you please open another issue for investigate this?

**Comment by amatya-aditya** [comment]
I am also encountering the same error as William, which he showed in one of his screenshots.

My screenshot is attached.

![Image](https://github.com/user-attachments/assets/5c18801b-bc9c-42db-ad10-685cb64d7487)

**Comment by Mara-Li** [comment]
William can't, if I understand well, send any file even using the command to push all.

So yes, could you please open another issue so I can track down?

I will probably try to write a "debug" command in the plugin to test in sequence with dummy file the plugin, but it requires a lot of time that I don't have...

**Comment by Mara-Li** [comment]
ALso, could you please try to install the last beta update ? So I'm sure that I'm work on the same version as your.

**Comment by Mara-Li** [comment]
Did you try on a fresh vault? What is the name of the vault?

**Comment by amatya-aditya** [comment]
Hi Mara-Li, thanks so much! I was using version 7.4.0 before, but I just updated to 7.5.0.1 and everything is working perfectly now. Thanks again for creating such an awesome plugin, I really think the name `envelope` is a great fit for it! ❤️

**Comment by Mara-Li** [comment]
❤️happy to see that somehow the bug was fixed!
I also changed the console so now error stack should be fixed too (beta for the moment, I need to add some fixes tomorrow)

**Comment by williamium3000** [comment]
Hi Mara,
I confirm its a network issue. After contacting the network provider, the problem get solved.

Thanks so much for your effort and everything!!


Best
William

**Comment by Mara-Li** [comment]
Good to know!! Thank you for helping too!!
